# syntax=docker/dockerfile:1

FROM golang:latest AS builder

WORKDIR /src
ENV GOTOOLCHAIN=auto
COPY v2/go.mod v2/go.sum ./
RUN go mod download
COPY v2/cmd/ ./cmd/
COPY v2/pkg/ ./pkg/
COPY v2/proto/ ./proto/

ARG TARGETOS=linux
ARG TARGETARCH=amd64
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
    go build -trimpath -ldflags="-s -w" -o /out/agw-worker ./cmd/agw-worker

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /out/agw-worker /usr/local/bin/agw-worker
USER 65532:65532
ENTRYPOINT ["/usr/local/bin/agw-worker"]
