package sandbox

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	batchv1 "k8s.io/api/batch/v1"
	corev1 "k8s.io/api/core/v1"
	apiequality "k8s.io/apimachinery/pkg/api/equality"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/util/validation"
	"sigs.k8s.io/controller-runtime/pkg/client"

	v1alpha1 "github.com/Astatide1337/agents-gateway/v3/api/v1alpha1"
	sandboxv1beta1 "sigs.k8s.io/agent-sandbox/api/v1beta1"
)

const (
	// ChildNameLabelKey binds generated PVCs to the Job child without using a
	// label selector that could accidentally include another run's resources.
	ChildNameLabelKey = "agents.astatide.com/child"

	jobSpecFingerprintAnnotationKey = "agents.astatide.com/job-spec-fingerprint"
	// JobSpecFingerprintAnnotationKey lets trusted read-only clients validate a
	// Job child without duplicating the private fingerprint implementation.
	JobSpecFingerprintAnnotationKey = jobSpecFingerprintAnnotationKey
	pvcSpecFingerprintAnnotationKey = "agents.astatide.com/pvc-spec-fingerprint"

	// These labels are generated by the Kubernetes Job controller/admission
	// path. They are not part of the caller-owned PodTemplate contract.
	jobControllerUIDLabel       = "batch.kubernetes.io/controller-uid"
	jobNameLabel                = "batch.kubernetes.io/job-name"
	legacyJobControllerUIDLabel = "controller-uid"
	legacyJobNameLabel          = "job-name"
)

var (
	// ErrJobSpecConflict is returned when an existing Job or generated PVC has
	// the right identity but a different immutable specification.
	ErrJobSpecConflict     = errors.New("sandbox job spec conflict")
	ErrMissingGeneratedPVC = errors.New("generated sandbox PVC is missing")
)

// JobBackend is the batch/v1 fallback for clusters where the upstream
// agent-sandbox controller is unavailable. It intentionally implements only
// the running, one-shot Sandbox shape used by v3; it never silently drops a
// service, lifecycle, or security property.
type JobBackend struct {
	client              client.Client
	now                 func() time.Time
	maxShutdownDuration time.Duration
}

// JobSandboxBackend is a descriptive alias kept for callers that name the
// backend after the Sandbox abstraction.
type JobSandboxBackend = JobBackend

var _ SandboxBackend = (*JobBackend)(nil)

// NewJobBackend constructs the Job fallback backend.
func NewJobBackend(c client.Client, options BackendOptions) (*JobBackend, error) {
	if c == nil {
		return nil, fmt.Errorf("%w: nil Kubernetes client", ErrInvalidPlan)
	}
	now := options.Now
	if now == nil {
		now = time.Now
	}
	maxShutdown := options.MaxShutdownDuration
	if maxShutdown == 0 {
		maxShutdown = DefaultMaxShutdownDuration
	}
	if maxShutdown <= 0 || maxShutdown > DefaultMaxShutdownDuration {
		return nil, fmt.Errorf("%w: max shutdown duration must be in (0,%s]", ErrInvalidPlan, DefaultMaxShutdownDuration)
	}
	return &JobBackend{client: c, now: now, maxShutdownDuration: maxShutdown}, nil
}

// NewJobSandboxBackend is an alias for NewJobBackend.
func NewJobSandboxBackend(c client.Client, options BackendOptions) (*JobBackend, error) {
	return NewJobBackend(c, options)
}

// Ensure is idempotent across retries and partial PVC/Job creation. PVCs are
// created before a new Job, but an existing Job is validated before any
// missing PVC is created. Neither existing resource is ever mutated.
func (b *JobBackend) Ensure(ctx context.Context, plan SandboxPlan) (SandboxRef, error) {
	_, expectedJob, expectedPVCs, expectedRef, err := b.prepare(plan)
	if err != nil {
		return SandboxRef{}, err
	}

	key := client.ObjectKey{Namespace: expectedJob.Namespace, Name: expectedJob.Name}
	var current batchv1.Job
	if err := b.client.Get(ctx, key, &current); err == nil {
		if err := b.validateExistingJob(&current, expectedJob, expectedRef); err != nil {
			return SandboxRef{}, err
		}
		if err := b.ensurePVCs(ctx, expectedPVCs, expectedRef); err != nil {
			return SandboxRef{}, err
		}
		return refFromJob(&current, expectedRef), nil
	} else if !apierrors.IsNotFound(err) {
		return SandboxRef{}, fmt.Errorf("get fallback Job %s/%s: %w", key.Namespace, key.Name, err)
	}

	if err := b.ensurePVCs(ctx, expectedPVCs, expectedRef); err != nil {
		return SandboxRef{}, err
	}
	if err := b.client.Create(ctx, expectedJob.DeepCopy()); err == nil {
		// Always read the created object. This captures the server UID and
		// server-side defaults used by subsequent Observe/Delete calls.
		current = batchv1.Job{}
		if err := b.client.Get(ctx, key, &current); err != nil {
			return SandboxRef{}, fmt.Errorf("get fallback Job after create %s/%s: %w", key.Namespace, key.Name, err)
		}
		if err := b.validateExistingJob(&current, expectedJob, expectedRef); err != nil {
			return SandboxRef{}, err
		}
		return refFromJob(&current, expectedRef), nil
	} else if !apierrors.IsAlreadyExists(err) {
		return SandboxRef{}, fmt.Errorf("create fallback Job %s/%s: %w", key.Namespace, key.Name, err)
	}

	// A concurrent creator is accepted only after a fresh full validation.
	current = batchv1.Job{}
	if err := b.client.Get(ctx, key, &current); err != nil {
		return SandboxRef{}, fmt.Errorf("get fallback Job after create race %s/%s: %w", key.Namespace, key.Name, err)
	}
	if err := b.validateExistingJob(&current, expectedJob, expectedRef); err != nil {
		return SandboxRef{}, err
	}
	if err := b.ensurePVCs(ctx, expectedPVCs, expectedRef); err != nil {
		return SandboxRef{}, err
	}
	return refFromJob(&current, expectedRef), nil
}

// Observe projects Job state into the bounded SandboxObservation contract.
// A Job is ready once it has active work or has reached a terminal condition;
// both Complete and Failed are terminal and therefore Finished.
func (b *JobBackend) Observe(ctx context.Context, ref SandboxRef) (SandboxObservation, error) {
	if err := validateRefKind(ref, ChildKindJob); err != nil {
		return SandboxObservation{}, err
	}
	key := client.ObjectKey{Namespace: ref.Namespace, Name: ref.Name}
	var current batchv1.Job
	if err := b.client.Get(ctx, key, &current); err != nil {
		if apierrors.IsNotFound(err) {
			return SandboxObservation{Ref: ref}, nil
		}
		return SandboxObservation{}, fmt.Errorf("get fallback Job %s/%s: %w", key.Namespace, key.Name, err)
	}
	if err := b.validateExistingJobIdentityAndShape(&current, ref); err != nil {
		return SandboxObservation{}, err
	}
	if err := b.validateReferencedPVCs(ctx, &current, ref); err != nil {
		return SandboxObservation{}, err
	}
	return observationFromJob(&current, ref)
}

// Delete removes only the owned Job. Generated PVCs are deliberately retained
// for the AgentRun retention/finalizer path and are never garbage-collected by
// this backend because their owner is the AgentRun, not the Job.
func (b *JobBackend) Delete(ctx context.Context, ref SandboxRef) error {
	if err := validateRefKind(ref, ChildKindJob); err != nil {
		return err
	}
	key := client.ObjectKey{Namespace: ref.Namespace, Name: ref.Name}
	var current batchv1.Job
	if err := b.client.Get(ctx, key, &current); err != nil {
		if apierrors.IsNotFound(err) {
			return nil
		}
		return fmt.Errorf("get fallback Job for delete %s/%s: %w", key.Namespace, key.Name, err)
	}
	if err := b.validateExistingJobIdentityAndShape(&current, ref); err != nil {
		return err
	}
	if err := b.validateReferencedPVCs(ctx, &current, ref); err != nil {
		return err
	}
	if err := b.client.Delete(ctx, &current, client.Preconditions{UID: &ref.UID}); err != nil && !apierrors.IsNotFound(err) {
		return fmt.Errorf("delete fallback Job %s/%s: %w", key.Namespace, key.Name, err)
	}
	return nil
}

// CleanupOwned removes a deterministic fallback Job when a controller crash
// occurred before its ChildRef reached AgentRun status. Generated PVCs remain
// for the retention controller, matching the normal Job Delete contract.
func (b *JobBackend) CleanupOwned(ctx context.Context, namespace string, ownerUID types.UID, role Role, specDigest string) error {
	if namespace == "" || ownerUID == "" || !role.valid() || !validDigest(specDigest) {
		return fmt.Errorf("%w: namespace, owner UID, role, and spec digest are required", ErrReferenceConflict)
	}
	name, err := ChildName(ownerUID, role)
	if err != nil {
		return err
	}
	var current batchv1.Job
	key := client.ObjectKey{Namespace: namespace, Name: name}
	if err := b.client.Get(ctx, key, &current); err != nil {
		if apierrors.IsNotFound(err) {
			return nil
		}
		return fmt.Errorf("get orphan Job %s/%s: %w", key.Namespace, key.Name, err)
	}
	ref := SandboxRef{
		Namespace: namespace, Name: name, Kind: ChildKindJob, UID: current.UID,
		OwnerUID: ownerUID, Role: role, SpecDigest: specDigest,
		PlanFingerprint: jobSpecFingerprint(current.Spec),
	}
	if err := b.validateExistingJobIdentityAndShape(&current, ref); err != nil {
		return err
	}
	if err := b.validateReferencedPVCs(ctx, &current, ref); err != nil {
		return err
	}
	if err := b.client.Delete(ctx, &current, client.Preconditions{UID: &current.UID}); err != nil && !apierrors.IsNotFound(err) {
		return fmt.Errorf("delete orphan Job %s/%s: %w", key.Namespace, key.Name, err)
	}
	return nil
}

func (b *JobBackend) prepare(plan SandboxPlan) (*sandboxv1beta1.Sandbox, *batchv1.Job, []*corev1.PersistentVolumeClaim, SandboxRef, error) {
	if plan.Owner == nil {
		return nil, nil, nil, SandboxRef{}, fmt.Errorf("%w: AgentRun owner is required", ErrInvalidPlan)
	}
	if plan.Owner.Namespace == "" || plan.Owner.Name == "" || plan.Owner.UID == "" {
		return nil, nil, nil, SandboxRef{}, fmt.Errorf("%w: owner namespace, name, and UID are required", ErrInvalidPlan)
	}
	if !plan.Role.valid() {
		return nil, nil, nil, SandboxRef{}, fmt.Errorf("%w: unsupported role %q", ErrInvalidPlan, plan.Role)
	}
	if !validDigest(plan.SpecDigest) {
		return nil, nil, nil, SandboxRef{}, fmt.Errorf("%w: spec digest must be sha256:<64 lowercase hex characters>", ErrInvalidPlan)
	}
	if plan.Sandbox == nil {
		return nil, nil, nil, SandboxRef{}, fmt.Errorf("%w: fully constructed upstream Sandbox is required", ErrInvalidPlan)
	}

	name, err := ChildName(plan.Owner.UID, plan.Role)
	if err != nil {
		return nil, nil, nil, SandboxRef{}, err
	}
	prepared := plan.Sandbox.DeepCopy()
	if prepared.Namespace != "" && prepared.Namespace != plan.Owner.Namespace {
		return nil, nil, nil, SandboxRef{}, fmt.Errorf("%w: Sandbox namespace %q does not match owner namespace %q", ErrInvalidPlan, prepared.Namespace, plan.Owner.Namespace)
	}
	if prepared.Name != "" && prepared.Name != name {
		return nil, nil, nil, SandboxRef{}, fmt.Errorf("%w: Sandbox name %q is not deterministic name %q", ErrInvalidPlan, prepared.Name, name)
	}
	prepared.APIVersion = sandboxv1beta1.GroupVersion.String()
	prepared.Kind = sandboxv1beta1.SandboxKind
	prepared.Namespace = plan.Owner.Namespace
	prepared.Name = name
	if err := stampMetadata(prepared, plan.Owner, plan.Role, plan.SpecDigest); err != nil {
		return nil, nil, nil, SandboxRef{}, err
	}
	if err := validateSandbox(prepared, plan.Role, b.now(), b.maxShutdownDuration, false); err != nil {
		return nil, nil, nil, SandboxRef{}, err
	}
	if prepared.Spec.Service != nil && *prepared.Spec.Service {
		return nil, nil, nil, SandboxRef{}, fmt.Errorf("%w: Job fallback does not support a Service", ErrInvalidSecurityPosture)
	}
	if prepared.Spec.OperatingMode != "" && prepared.Spec.OperatingMode != sandboxv1beta1.SandboxOperatingModeRunning {
		return nil, nil, nil, SandboxRef{}, fmt.Errorf("%w: Job fallback supports only Running operatingMode", ErrInvalidSecurityPosture)
	}

	ref := SandboxRef{Namespace: prepared.Namespace, Name: prepared.Name, Kind: ChildKindJob, OwnerUID: plan.Owner.UID, Role: plan.Role, SpecDigest: plan.SpecDigest}
	job, pvcs, err := buildJobAndPVCs(prepared, plan.Owner, ref, b.now())
	if err != nil {
		return nil, nil, nil, SandboxRef{}, err
	}
	ref.PlanFingerprint = jobSpecFingerprint(job.Spec)
	return prepared, job, pvcs, ref, nil
}

func buildJobAndPVCs(sandbox *sandboxv1beta1.Sandbox, owner *v1alpha1.AgentRun, ref SandboxRef, now time.Time) (*batchv1.Job, []*corev1.PersistentVolumeClaim, error) {
	podSpec := sandbox.Spec.PodTemplate.Spec.DeepCopy()
	if err := rejectServerOwnedTemplateLabels(sandbox.Spec.PodTemplate.ObjectMeta.Labels); err != nil {
		return nil, nil, err
	}
	claimNames := make(map[string]string, len(sandbox.Spec.VolumeClaimTemplates))
	pvcs := make([]*corev1.PersistentVolumeClaim, 0, len(sandbox.Spec.VolumeClaimTemplates))
	for _, template := range sandbox.Spec.VolumeClaimTemplates {
		if template.Name == "" {
			return nil, nil, fmt.Errorf("%w: volume claim template name is required", ErrInvalidPlan)
		}
		if errs := validation.IsDNS1123Subdomain(template.Name); len(errs) != 0 {
			return nil, nil, fmt.Errorf("%w: invalid volume claim template name %q: %s", ErrInvalidPlan, template.Name, strings.Join(errs, "; "))
		}
		if _, exists := claimNames[template.Name]; exists {
			return nil, nil, fmt.Errorf("%w: duplicate volume claim template %q", ErrInvalidPlan, template.Name)
		}
		claimName := template.Name + "-" + sandbox.Name
		if errs := validation.IsDNS1123Subdomain(claimName); len(errs) != 0 {
			return nil, nil, fmt.Errorf("%w: generated PVC name %q is invalid: %s", ErrInvalidPlan, claimName, strings.Join(errs, "; "))
		}
		claimNames[template.Name] = claimName

		labels, err := reservedMap(template.Labels, map[string]string{
			RunUIDLabelKey:     string(owner.UID),
			RoleLabelKey:       string(ref.Role),
			SpecDigestLabelKey: digestLabelValue(ref.SpecDigest),
			ChildNameLabelKey:  ref.Name,
		})
		if err != nil {
			return nil, nil, fmt.Errorf("%w: PVC %q labels: %v", ErrInvalidPlan, template.Name, err)
		}
		annotations, err := reservedMap(template.Annotations, map[string]string{SpecDigestAnnotationKey: ref.SpecDigest})
		if err != nil {
			return nil, nil, fmt.Errorf("%w: PVC %q annotations: %v", ErrInvalidPlan, template.Name, err)
		}
		pvc := &corev1.PersistentVolumeClaim{
			TypeMeta: metav1.TypeMeta{APIVersion: corev1.SchemeGroupVersion.String(), Kind: "PersistentVolumeClaim"},
			ObjectMeta: metav1.ObjectMeta{
				Name:            claimName,
				Namespace:       sandbox.Namespace,
				Labels:          labels,
				Annotations:     annotations,
				OwnerReferences: []metav1.OwnerReference{agentRunOwnerReference(owner)},
			},
			Spec: *template.Spec.DeepCopy(),
		}
		pvc.Annotations[pvcSpecFingerprintAnnotationKey] = pvcSpecFingerprint(pvc.Spec)
		pvcs = append(pvcs, pvc)
	}

	for index := range podSpec.Volumes {
		volume := &podSpec.Volumes[index]
		if volume.PersistentVolumeClaim == nil {
			continue
		}
		if claimName, ok := claimNames[volume.PersistentVolumeClaim.ClaimName]; ok {
			volume.PersistentVolumeClaim.ClaimName = claimName
		}
	}

	labels, err := reservedMap(sandbox.Labels, map[string]string{ChildNameLabelKey: ref.Name})
	if err != nil {
		return nil, nil, fmt.Errorf("%w: Job labels: %v", ErrInvalidPlan, err)
	}
	annotations, err := reservedMap(sandbox.Annotations, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("%w: Job annotations: %v", ErrInvalidPlan, err)
	}
	job := &batchv1.Job{
		TypeMeta: metav1.TypeMeta{APIVersion: batchv1.SchemeGroupVersion.String(), Kind: "Job"},
		ObjectMeta: metav1.ObjectMeta{
			Name:            sandbox.Name,
			Namespace:       sandbox.Namespace,
			Labels:          labels,
			Annotations:     annotations,
			OwnerReferences: []metav1.OwnerReference{agentRunOwnerReference(owner)},
		},
		Spec: batchv1.JobSpec{
			Parallelism:           int32Ptr(1),
			Completions:           int32Ptr(1),
			ActiveDeadlineSeconds: activeDeadlineSeconds(sandbox.Spec.ShutdownTime.Time, now),
			BackoffLimit:          int32Ptr(0),
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{
					Labels:      cloneStringMap(sandbox.Spec.PodTemplate.ObjectMeta.Labels),
					Annotations: cloneStringMap(sandbox.Spec.PodTemplate.ObjectMeta.Annotations),
				},
				Spec: *podSpec,
			},
		},
	}
	job.Annotations[jobSpecFingerprintAnnotationKey] = jobSpecFingerprint(job.Spec)
	return job, pvcs, nil
}

func (b *JobBackend) ensurePVCs(ctx context.Context, expected []*corev1.PersistentVolumeClaim, ref SandboxRef) error {
	if err := b.validateUnexpectedPVCs(ctx, expected, ref); err != nil {
		return err
	}
	for _, desired := range expected {
		key := client.ObjectKeyFromObject(desired)
		var current corev1.PersistentVolumeClaim
		if err := b.client.Get(ctx, key, &current); err == nil {
			if err := validateExistingPVC(&current, desired, ref); err != nil {
				return err
			}
			continue
		} else if !apierrors.IsNotFound(err) {
			return fmt.Errorf("get fallback PVC %s/%s: %w", key.Namespace, key.Name, err)
		}
		if err := b.client.Create(ctx, desired.DeepCopy()); err == nil {
			continue
		} else if !apierrors.IsAlreadyExists(err) {
			return fmt.Errorf("create fallback PVC %s/%s: %w", key.Namespace, key.Name, err)
		}
		current = corev1.PersistentVolumeClaim{}
		if err := b.client.Get(ctx, key, &current); err != nil {
			return fmt.Errorf("get fallback PVC after create race %s/%s: %w", key.Namespace, key.Name, err)
		}
		if err := validateExistingPVC(&current, desired, ref); err != nil {
			return err
		}
	}
	return nil
}

func (b *JobBackend) validateUnexpectedPVCs(ctx context.Context, expected []*corev1.PersistentVolumeClaim, ref SandboxRef) error {
	var list corev1.PersistentVolumeClaimList
	if err := b.client.List(ctx, &list, client.InNamespace(ref.Namespace), client.MatchingLabels{ChildNameLabelKey: ref.Name}); err != nil {
		return fmt.Errorf("list fallback PVCs for %s/%s: %w", ref.Namespace, ref.Name, err)
	}
	want := make(map[string]*corev1.PersistentVolumeClaim, len(expected))
	for _, pvc := range expected {
		want[pvc.Name] = pvc
	}
	for index := range list.Items {
		current := &list.Items[index]
		desired, ok := want[current.Name]
		if !ok {
			return fmt.Errorf("%w: unexpected generated PVC %s/%s", ErrReferenceConflict, current.Namespace, current.Name)
		}
		if err := validateExistingPVC(current, desired, ref); err != nil {
			return err
		}
	}
	return nil
}

func (b *JobBackend) validateReferencedPVCs(ctx context.Context, job *batchv1.Job, ref SandboxRef) error {
	seen := make(map[string]struct{})
	suffix := "-" + ref.Name
	for _, volume := range job.Spec.Template.Spec.Volumes {
		if volume.PersistentVolumeClaim == nil || !strings.HasSuffix(volume.PersistentVolumeClaim.ClaimName, suffix) {
			continue
		}
		claimName := volume.PersistentVolumeClaim.ClaimName
		if _, ok := seen[claimName]; ok {
			continue
		}
		seen[claimName] = struct{}{}
		var pvc corev1.PersistentVolumeClaim
		if err := b.client.Get(ctx, client.ObjectKey{Namespace: ref.Namespace, Name: claimName}, &pvc); err != nil {
			if apierrors.IsNotFound(err) {
				return fmt.Errorf("%w: referenced generated PVC %s/%s", ErrMissingGeneratedPVC, ref.Namespace, claimName)
			}
			return fmt.Errorf("get referenced fallback PVC %s/%s: %w", ref.Namespace, claimName, err)
		}
		if err := validatePVCIdentity(&pvc, ref); err != nil {
			return err
		}
	}

	var list corev1.PersistentVolumeClaimList
	if err := b.client.List(ctx, &list, client.InNamespace(ref.Namespace), client.MatchingLabels{ChildNameLabelKey: ref.Name}); err != nil {
		return fmt.Errorf("list referenced fallback PVCs for %s/%s: %w", ref.Namespace, ref.Name, err)
	}
	for index := range list.Items {
		if err := validatePVCIdentity(&list.Items[index], ref); err != nil {
			return err
		}
	}
	return nil
}

func (b *JobBackend) validateExistingJobIdentityAndShape(job *batchv1.Job, ref SandboxRef) error {
	if err := validateJobIdentity(job, ref); err != nil {
		return err
	}
	return b.validateJobShape(job, ref.Role)
}

func (b *JobBackend) validateExistingJob(job, expected *batchv1.Job, ref SandboxRef) error {
	if err := b.validateExistingJobIdentityAndShape(job, ref); err != nil {
		return err
	}
	if jobSpecFingerprint(job.Spec) != expected.Annotations[jobSpecFingerprintAnnotationKey] || !sameJobSpec(job.Spec, expected.Spec) {
		return fmt.Errorf("%w: Job %s/%s does not match the immutable plan", ErrJobSpecConflict, job.Namespace, job.Name)
	}
	return nil
}

func (b *JobBackend) validateJobShape(job *batchv1.Job, role Role) error {
	maxSeconds := int64(b.maxShutdownDuration / time.Second)
	if b.maxShutdownDuration%time.Second != 0 {
		maxSeconds++
	}
	if job.Spec.ActiveDeadlineSeconds == nil || *job.Spec.ActiveDeadlineSeconds <= 0 || *job.Spec.ActiveDeadlineSeconds > maxSeconds {
		return fmt.Errorf("%w: Job activeDeadlineSeconds is outside the allowed bound", ErrInvalidSecurityPosture)
	}
	if job.Spec.BackoffLimit == nil || *job.Spec.BackoffLimit != 0 {
		return fmt.Errorf("%w: Job backoffLimit must be zero", ErrInvalidSecurityPosture)
	}
	if job.Spec.Parallelism == nil || *job.Spec.Parallelism != 1 || job.Spec.Completions == nil || *job.Spec.Completions != 1 {
		return fmt.Errorf("%w: Job must have parallelism and completions equal to one", ErrInvalidSecurityPosture)
	}
	if job.Spec.Suspend != nil && *job.Spec.Suspend {
		return fmt.Errorf("%w: suspended Jobs are unsupported", ErrInvalidSecurityPosture)
	}
	if job.Spec.ManualSelector != nil && *job.Spec.ManualSelector {
		return fmt.Errorf("%w: manual Job selectors are unsupported", ErrInvalidSecurityPosture)
	}
	if job.Spec.CompletionMode != nil && *job.Spec.CompletionMode != batchv1.NonIndexedCompletion {
		return fmt.Errorf("%w: indexed Jobs are unsupported", ErrInvalidSecurityPosture)
	}
	if job.Spec.PodReplacementPolicy != nil && *job.Spec.PodReplacementPolicy != batchv1.TerminatingOrFailed {
		return fmt.Errorf("%w: unsupported Job pod replacement policy is set", ErrInvalidSecurityPosture)
	}
	if job.Spec.PodFailurePolicy != nil || job.Spec.SuccessPolicy != nil || job.Spec.BackoffLimitPerIndex != nil || job.Spec.MaxFailedIndexes != nil || job.Spec.TTLSecondsAfterFinished != nil || job.Spec.ManagedBy != nil {
		return fmt.Errorf("%w: unsupported Job lifecycle policy is set", ErrInvalidSecurityPosture)
	}
	shutdown := metav1.NewTime(b.now())
	policy := sandboxv1beta1.ShutdownPolicyDelete
	synthetic := &sandboxv1beta1.Sandbox{Spec: sandboxv1beta1.SandboxSpec{
		SandboxBlueprint: sandboxv1beta1.SandboxBlueprint{PodTemplate: sandboxv1beta1.PodTemplate{Spec: *job.Spec.Template.Spec.DeepCopy()}},
		Lifecycle:        sandboxv1beta1.Lifecycle{ShutdownTime: &shutdown, ShutdownPolicy: &policy},
	}}
	if err := validateSandbox(synthetic, role, b.now(), b.maxShutdownDuration, true); err != nil {
		return err
	}
	return nil
}

func validateJobIdentity(job *batchv1.Job, ref SandboxRef) error {
	if job.Namespace != ref.Namespace || job.Name != ref.Name {
		return fmt.Errorf("%w: object is %s/%s, reference is %s/%s", ErrReferenceConflict, job.Namespace, job.Name, ref.Namespace, ref.Name)
	}
	if ref.UID != "" && job.UID != "" && ref.UID != job.UID {
		return fmt.Errorf("%w: Job UID %q differs from reference UID %q", ErrReferenceConflict, job.UID, ref.UID)
	}
	if !hasExpectedJobOwner(job, ref) {
		return fmt.Errorf("%w: Job %s/%s is not controlled by AgentRun UID %q", ErrForeignChild, job.Namespace, job.Name, ref.OwnerUID)
	}
	if job.Labels[RunUIDLabelKey] != string(ref.OwnerUID) || job.Labels[RoleLabelKey] != string(ref.Role) || job.Labels[ChildNameLabelKey] != ref.Name {
		return fmt.Errorf("%w: Job ownership labels do not match reference", ErrForeignChild)
	}
	if job.Labels[SpecDigestLabelKey] != digestLabelValue(ref.SpecDigest) || job.Annotations[SpecDigestAnnotationKey] != ref.SpecDigest {
		return fmt.Errorf("%w: expected %q, found Job label %q and annotation %q", ErrSpecDigestConflict, ref.SpecDigest, job.Labels[SpecDigestLabelKey], job.Annotations[SpecDigestAnnotationKey])
	}
	actualFingerprint := jobSpecFingerprint(job.Spec)
	if actualFingerprint != ref.PlanFingerprint {
		return fmt.Errorf("%w: Job actual spec fingerprint %q differs from persisted plan fingerprint %q", ErrJobSpecConflict, actualFingerprint, ref.PlanFingerprint)
	}
	if job.Annotations[jobSpecFingerprintAnnotationKey] != ref.PlanFingerprint {
		return fmt.Errorf("%w: Job spec fingerprint annotation differs from persisted plan fingerprint", ErrJobSpecConflict)
	}
	return nil
}

func validateExistingPVC(current, expected *corev1.PersistentVolumeClaim, ref SandboxRef) error {
	if current.Namespace != expected.Namespace || current.Name != expected.Name {
		return fmt.Errorf("%w: PVC is %s/%s, expected %s/%s", ErrReferenceConflict, current.Namespace, current.Name, expected.Namespace, expected.Name)
	}
	if !hasExpectedPVCOwner(current, ref) {
		return fmt.Errorf("%w: PVC %s/%s is not controlled by AgentRun UID %q", ErrForeignChild, current.Namespace, current.Name, ref.OwnerUID)
	}
	if err := validatePVCIdentity(current, ref); err != nil {
		return err
	}
	if current.Annotations[pvcSpecFingerprintAnnotationKey] != expected.Annotations[pvcSpecFingerprintAnnotationKey] || !apiequality.Semantic.DeepEqual(current.Spec, expected.Spec) {
		return fmt.Errorf("%w: PVC %s/%s does not match the immutable plan", ErrJobSpecConflict, current.Namespace, current.Name)
	}
	return nil
}

func validatePVCIdentity(pvc *corev1.PersistentVolumeClaim, ref SandboxRef) error {
	if pvc.Namespace != ref.Namespace {
		return fmt.Errorf("%w: PVC namespace %q differs from reference namespace %q", ErrReferenceConflict, pvc.Namespace, ref.Namespace)
	}
	if !strings.HasSuffix(pvc.Name, "-"+ref.Name) {
		return fmt.Errorf("%w: PVC name %q is not derived from child %q", ErrForeignChild, pvc.Name, ref.Name)
	}
	if !hasExpectedPVCOwner(pvc, ref) {
		return fmt.Errorf("%w: PVC %s/%s is not controlled by AgentRun UID %q", ErrForeignChild, pvc.Namespace, pvc.Name, ref.OwnerUID)
	}
	if pvc.Labels[RunUIDLabelKey] != string(ref.OwnerUID) || pvc.Labels[RoleLabelKey] != string(ref.Role) || pvc.Labels[ChildNameLabelKey] != ref.Name {
		return fmt.Errorf("%w: PVC ownership labels do not match reference", ErrForeignChild)
	}
	if pvc.Labels[SpecDigestLabelKey] != digestLabelValue(ref.SpecDigest) || pvc.Annotations[SpecDigestAnnotationKey] != ref.SpecDigest {
		return fmt.Errorf("%w: expected %q, found PVC label %q and annotation %q", ErrSpecDigestConflict, ref.SpecDigest, pvc.Labels[SpecDigestLabelKey], pvc.Annotations[SpecDigestAnnotationKey])
	}
	if pvc.Annotations[pvcSpecFingerprintAnnotationKey] != pvcSpecFingerprint(pvc.Spec) {
		return fmt.Errorf("%w: PVC spec fingerprint is missing or does not match its immutable spec", ErrJobSpecConflict)
	}
	return nil
}

func hasExpectedJobOwner(job *batchv1.Job, ref SandboxRef) bool {
	if len(job.OwnerReferences) != 1 {
		return false
	}
	owner := job.OwnerReferences[0]
	return owner.APIVersion == ownerAPIVersion && owner.Kind == ownerKind && owner.Name != "" && owner.UID == ref.OwnerUID && boolValue(owner.Controller) && boolValue(owner.BlockOwnerDeletion)
}

func hasExpectedPVCOwner(pvc *corev1.PersistentVolumeClaim, ref SandboxRef) bool {
	if len(pvc.OwnerReferences) != 1 {
		return false
	}
	owner := pvc.OwnerReferences[0]
	return owner.APIVersion == ownerAPIVersion && owner.Kind == ownerKind && owner.Name != "" && owner.UID == ref.OwnerUID && boolValue(owner.Controller) && boolValue(owner.BlockOwnerDeletion)
}

func refFromJob(job *batchv1.Job, expected SandboxRef) SandboxRef {
	expected.Namespace = job.Namespace
	expected.Name = job.Name
	expected.UID = job.UID
	return expected
}

func observationFromJob(job *batchv1.Job, expected SandboxRef) (SandboxObservation, error) {
	if len(job.Status.Conditions) > MaxObservedConditions {
		return SandboxObservation{}, fmt.Errorf("%w: %d conditions exceeds %d", ErrObservationTooLarge, len(job.Status.Conditions), MaxObservedConditions)
	}
	observation := SandboxObservation{Ref: refFromJob(job, expected), Exists: true, Conditions: make([]ConditionObservation, 0, len(job.Status.Conditions))}
	terminal := job.Status.Succeeded > 0 || job.Status.Failed > 0
	for _, condition := range job.Status.Conditions {
		observation.Conditions = append(observation.Conditions, ConditionObservation{
			Type:               string(condition.Type),
			Status:             metav1.ConditionStatus(condition.Status),
			Reason:             condition.Reason,
			ObservedGeneration: 0,
			LastTransitionTime: condition.LastTransitionTime,
		})
		if condition.Status != corev1.ConditionTrue {
			continue
		}
		switch condition.Type {
		case batchv1.JobComplete, batchv1.JobFailed:
			terminal = true
		}
	}
	observation.Finished = terminal
	observation.Ready = terminal || job.Status.Active > 0
	return observation, nil
}

func agentRunOwnerReference(owner *v1alpha1.AgentRun) metav1.OwnerReference {
	return metav1.OwnerReference{APIVersion: ownerAPIVersion, Kind: ownerKind, Name: owner.Name, UID: owner.UID, Controller: boolPtr(true), BlockOwnerDeletion: boolPtr(true)}
}

func reservedMap(input map[string]string, reserved map[string]string) (map[string]string, error) {
	output := cloneStringMap(input)
	if output == nil {
		output = make(map[string]string, len(reserved))
	}
	for key, value := range reserved {
		if current, ok := output[key]; ok && current != value {
			return nil, fmt.Errorf("reserved key %q is %q, want %q", key, current, value)
		}
		output[key] = value
	}
	return output, nil
}

func cloneStringMap(input map[string]string) map[string]string {
	if input == nil {
		return nil
	}
	output := make(map[string]string, len(input))
	for key, value := range input {
		output[key] = value
	}
	return output
}

func activeDeadlineSeconds(shutdown, now time.Time) *int64 {
	duration := shutdown.Sub(now)
	if duration <= 0 {
		duration = time.Second
	}
	seconds := int64(duration / time.Second)
	if duration%time.Second != 0 {
		seconds++
	}
	if seconds < 1 {
		seconds = 1
	}
	return &seconds
}

func int32Ptr(value int32) *int32 { return &value }

func jobInt64Ptr(value int64) *int64 { return &value }

func sameJobSpec(current, expected batchv1.JobSpec) bool {
	left := normalizedJobSpec(current)
	right := normalizedJobSpec(expected)
	return apiequality.Semantic.DeepEqual(left, right)
}

func normalizedJobSpec(input batchv1.JobSpec) batchv1.JobSpec {
	output := *input.DeepCopy()
	// Selector is generated by the apiserver and is intentionally not part of
	// the caller-owned contract.
	output.Selector = nil
	// These fields have stable Kubernetes defaults. Treat nil and the
	// apiserver's explicit default as the same value, while still rejecting a
	// non-default caller mutation in validateJobShape.
	if output.ManualSelector == nil {
		output.ManualSelector = boolPtr(false)
	}
	if output.Suspend == nil {
		output.Suspend = boolPtr(false)
	}
	if output.CompletionMode == nil {
		mode := batchv1.NonIndexedCompletion
		output.CompletionMode = &mode
	}
	if output.PodReplacementPolicy == nil {
		policy := batchv1.TerminatingOrFailed
		output.PodReplacementPolicy = &policy
	}
	output.Template.ObjectMeta.Labels = normalizeServerOwnedTemplateLabels(output.Template.ObjectMeta.Labels)
	normalizePodSpec(&output.Template.Spec)
	return output
}

func normalizePodSpec(pod *corev1.PodSpec) {
	if pod.DNSPolicy == "" {
		pod.DNSPolicy = corev1.DNSClusterFirst
	}
	if pod.SchedulerName == "" {
		pod.SchedulerName = corev1.DefaultSchedulerName
	}
	if pod.EnableServiceLinks == nil {
		pod.EnableServiceLinks = boolPtr(true)
	}
	if pod.TerminationGracePeriodSeconds == nil {
		pod.TerminationGracePeriodSeconds = jobInt64Ptr(30)
	}
	if pod.PreemptionPolicy == nil {
		policy := corev1.PreemptLowerPriority
		pod.PreemptionPolicy = &policy
	}
	if pod.Priority == nil {
		priority := int32(0)
		pod.Priority = &priority
	}
	for index := range pod.InitContainers {
		normalizeContainer(&pod.InitContainers[index])
	}
	for index := range pod.Containers {
		normalizeContainer(&pod.Containers[index])
	}
}

func normalizeContainer(container *corev1.Container) {
	if container.ImagePullPolicy == "" {
		container.ImagePullPolicy = defaultImagePullPolicy(container.Image)
	}
	if container.TerminationMessagePath == "" {
		container.TerminationMessagePath = corev1.TerminationMessagePathDefault
	}
	if container.TerminationMessagePolicy == "" {
		container.TerminationMessagePolicy = corev1.TerminationMessageReadFile
	}
	if len(container.Resources.Limits) == 0 {
		container.Resources.Limits = nil
	}
	if len(container.Resources.Requests) == 0 {
		container.Resources.Requests = nil
	}
	if len(container.Resources.Claims) == 0 {
		container.Resources.Claims = nil
	}
}

func defaultImagePullPolicy(image string) corev1.PullPolicy {
	if strings.Contains(image, "@") {
		return corev1.PullIfNotPresent
	}
	lastSlash := strings.LastIndexByte(image, '/')
	lastColon := strings.LastIndexByte(image, ':')
	if lastColon <= lastSlash || lastColon == len(image)-1 || image[lastColon+1:] == "latest" {
		return corev1.PullAlways
	}
	return corev1.PullIfNotPresent
}

func rejectServerOwnedTemplateLabels(labels map[string]string) error {
	for _, key := range serverOwnedTemplateLabelKeys() {
		if _, ok := labels[key]; ok {
			return fmt.Errorf("%w: PodTemplate label %q is reserved for Kubernetes Job ownership", ErrInvalidPlan, key)
		}
	}
	return nil
}

func normalizeServerOwnedTemplateLabels(input map[string]string) map[string]string {
	output := cloneStringMap(input)
	for _, key := range serverOwnedTemplateLabelKeys() {
		delete(output, key)
	}
	if len(output) == 0 {
		return nil
	}
	return output
}

func serverOwnedTemplateLabelKeys() []string {
	return []string{jobControllerUIDLabel, jobNameLabel, legacyJobControllerUIDLabel, legacyJobNameLabel}
}

func jobSpecFingerprint(spec batchv1.JobSpec) string {
	digest := sha256.Sum256(mustJSON(normalizedJobSpec(spec)))
	return "sha256:" + hex.EncodeToString(digest[:])
}

func pvcSpecFingerprint(spec corev1.PersistentVolumeClaimSpec) string {
	copy := *spec.DeepCopy()
	if copy.VolumeMode == nil {
		mode := corev1.PersistentVolumeFilesystem
		copy.VolumeMode = &mode
	}
	digest := sha256.Sum256(mustJSON(copy))
	return "sha256:" + hex.EncodeToString(digest[:])
}

func mustJSON(value any) []byte {
	encoded, err := json.Marshal(value)
	if err != nil {
		panic(fmt.Sprintf("sandbox fingerprint JSON encoding failed: %v", err))
	}
	return encoded
}
