# syntax=docker/dockerfile:1

ARG GO_IMAGE=docker.io/library/golang:1.26.5@sha256:7caba5286b4c3613a337b709c573047d8ae62ee76106647313b61e72b99f20af
ARG COSIGN_SOURCE_COMMIT=11926fa5bbbbde47e88fc006b625a17769b743b2
ARG COSIGN_SOURCE_SHA256=3a718446bac51466efff6853639e1ca108b456ecbf07cd92938f548715d22d6b
ARG COSIGN_X_TEXT_VERSION=v0.40.0
ARG COSIGN_GRPC_VERSION=v1.82.1

FROM ${GO_IMAGE} AS build
WORKDIR /src
COPY v3/go.mod v3/go.sum ./
RUN go mod download
COPY v3/ ./
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -trimpath -buildvcs=false -ldflags='-s -w' \
    -o /out/agw-operator ./cmd/agw-operator

FROM ${GO_IMAGE} AS cosign
ARG COSIGN_SOURCE_COMMIT
ARG COSIGN_SOURCE_SHA256
ARG COSIGN_X_TEXT_VERSION
ARG COSIGN_GRPC_VERSION
WORKDIR /src/cosign
ADD https://github.com/sigstore/cosign/archive/${COSIGN_SOURCE_COMMIT}.tar.gz /tmp/cosign.tar.gz
RUN echo "${COSIGN_SOURCE_SHA256}  /tmp/cosign.tar.gz" | sha256sum -c - \
    && tar -xzf /tmp/cosign.tar.gz --strip-components=1 -C /src/cosign \
    && go mod edit -require="golang.org/x/text@${COSIGN_X_TEXT_VERSION}" \
        -require="google.golang.org/grpc@${COSIGN_GRPC_VERSION}" \
    && go mod download \
    && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
        go build -mod=mod -trimpath -buildvcs=false -ldflags='-s -w' \
        -o /out/cosign ./cmd/cosign

FROM docker.io/library/alpine:3.22.5@sha256:7c8cb692ae09657cbc4a3f3cbd0e8d5a2690ba38386aaaf252dbb060bf5eb2e6
ARG VCS_REF=unknown
ARG BUILD_DATE=unknown

LABEL org.opencontainers.image.title="Agents Gateway operator" \
      org.opencontainers.image.description="Kubernetes-native control plane for Agents Gateway v3" \
      org.opencontainers.image.source="https://github.com/Astatide1337/agents-gateway" \
      org.opencontainers.image.revision="${VCS_REF}" \
      org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.licenses="MIT AND Apache-2.0" \
      com.astatide.agw.component="operator" \
      com.astatide.agw.api="agents.astatide.com/v1alpha1"

RUN apk add --no-cache ca-certificates tzdata \
    && addgroup -S -g 65532 agw \
    && adduser -S -D -H -u 65532 -G agw -s /sbin/nologin agw \
    && install -d -m 0755 /agw \
    && install -d -m 0700 -o 65532 -g 65532 /tmp/k8s-webhook-server/serving-certs

COPY --from=build /out/agw-operator /agw/operator
COPY --from=cosign /out/cosign /usr/local/bin/cosign
RUN chmod 0755 /agw/operator

USER 65532:65532
WORKDIR /agw
ENTRYPOINT ["/agw/operator"]
