// Package orchestration composes the HTTP control plane with Temporal without
// coupling either transport package to the other.
package orchestration

import (
	"context"
	"errors"
	"fmt"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/Astatide1337/agents-gateway/v2/pkg/httpapi"
	"github.com/Astatide1337/agents-gateway/v2/pkg/runner"
	"github.com/Astatide1337/agents-gateway/v2/pkg/spec"
	"github.com/Astatide1337/agents-gateway/v2/pkg/store"
	agentworkflow "github.com/Astatide1337/agents-gateway/v2/pkg/workflow"
	"go.temporal.io/api/enums/v1"
	"go.temporal.io/api/serviceerror"
	"go.temporal.io/sdk/client"
)

const DefaultTaskQueue = "agents-gateway-v2"

var identifierPattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$`)

// TemporalExecutor is the narrow subset of the Temporal client used when a
// run is accepted. Keeping this boundary small makes duplicate dispatch and
// compilation behavior testable without a Temporal server.
type TemporalExecutor interface {
	ExecuteWorkflow(context.Context, client.StartWorkflowOptions, interface{}, ...interface{}) (client.WorkflowRun, error)
}

// TemporalSignaler is the small Temporal surface needed by public run signal
// endpoints. Keeping it separate from TemporalExecutor preserves focused unit
// tests and prevents an HTTP handler from depending on the full SDK client.
type TemporalSignaler interface {
	SignalWorkflow(context.Context, string, string, string, interface{}) error
}

type Starter struct {
	Store     store.Store
	Temporal  TemporalExecutor
	Signals   TemporalSignaler
	TaskQueue string
}

// Compiler resolves immutable resources into the engine-neutral workflow
// manifest consumed by either the standalone or Temporal run engine.
type Compiler struct {
	Store store.Store
	// SandboxUser is the non-root numeric uid[:gid] used inside sandboxes.
	// Rootless Podman standalone installs set this to the dedicated runner UID
	// so bind-mounted workspaces remain writable without host-level chown.
	SandboxUser string
}

func (s Starter) StartRun(ctx context.Context, request httpapi.RunStartRequest) error {
	if s.Store == nil || s.Temporal == nil {
		return errors.New("store and Temporal client are required")
	}
	if err := request.Scope.Validate(); err != nil {
		return err
	}
	if request.Run.ID == "" || request.Run.DefinitionDigest == "" {
		return errors.New("run id and definition digest are required")
	}
	manifest, err := s.compile(ctx, request)
	if err != nil {
		return err
	}
	taskQueue := strings.TrimSpace(s.TaskQueue)
	if taskQueue == "" {
		taskQueue = DefaultTaskQueue
	}
	_, err = s.Temporal.ExecuteWorkflow(ctx, client.StartWorkflowOptions{
		ID:                    request.Run.ID,
		TaskQueue:             taskQueue,
		WorkflowIDReusePolicy: enums.WORKFLOW_ID_REUSE_POLICY_REJECT_DUPLICATE,
	}, agentworkflow.WorkflowName, agentworkflow.WorkflowInput{
		OrganizationID: request.Scope.OrganizationID,
		ProjectID:      request.Scope.ProjectID,
		RunID:          request.Run.ID,
		Manifest:       manifest,
		InputRef:       request.InputRef,
	})
	if err == nil {
		return nil
	}
	var alreadyStarted *serviceerror.WorkflowExecutionAlreadyStarted
	if errors.As(err, &alreadyStarted) {
		// The database run id is immutable and the workflow id equals it. A retry
		// therefore confirms the already-started execution instead of creating a
		// second workflow.
		return nil
	}
	return fmt.Errorf("start Temporal workflow: %w", err)
}

// SignalRun delivers a public control command to the existing execution. A
// workflow-level signal uses runID; an agent-targeted signal uses the exact
// child ID generated by workflow.childWorkflowID: runID/agent/stepID. Signal
// delivery never starts or retargets an execution.
func (s Starter) SignalRun(ctx context.Context, scope store.Scope, runID string, signal httpapi.RunSignal) error {
	if s.Signals == nil {
		return errors.New("Temporal signal client is required")
	}
	if err := scope.Validate(); err != nil {
		return err
	}
	if err := validateWorkflowID(runID); err != nil {
		return err
	}
	target := signal.Target
	if target == "" {
		target = "workflow"
	}
	if target != "workflow" && target != "agent" {
		return errors.New("signal target must be workflow or agent")
	}
	workflowID := runID
	if target == "agent" {
		if err := validateWorkflowID(signal.StepID); err != nil {
			return errors.New("agent signal requires a valid step id")
		}
		workflowID = runID + "/agent/" + signal.StepID
	}
	var signalName string
	var argument interface{}
	switch signal.Kind {
	case "cancel":
		if target != "workflow" {
			return errors.New("cancel signals must target the workflow")
		}
		signalName = agentworkflow.SignalCancel
		argument = agentworkflow.CancelSignal{Reason: signal.Reason}
	case "approval":
		signalName = agentworkflow.SignalApproval
		argument = agentworkflow.ApprovalSignal{ApprovalID: signal.ApprovalID, StepID: signal.StepID, Decision: signal.Decision}
	case "reply":
		signalName = agentworkflow.SignalUserReply
		argument = agentworkflow.UserReplySignal{RunID: runID, StepID: signal.StepID, TaskID: signal.TaskID, ReplyRef: signal.ReplyRef}
	default:
		return errors.New("unsupported run signal")
	}
	if err := s.Signals.SignalWorkflow(ctx, workflowID, "", signalName, argument); err != nil {
		var notFound *serviceerror.NotFound
		if errors.As(err, &notFound) {
			return fmt.Errorf("%w: %v", httpapi.ErrWorkflowNotFound, err)
		}
		return fmt.Errorf("deliver %s signal: %w", signal.Kind, err)
	}
	return nil
}

func validateWorkflowID(value string) error {
	if value == "" || len(value) > 128 || !identifierPattern.MatchString(value) {
		return errors.New("workflow identifier is invalid")
	}
	return nil
}

func (s Starter) compile(ctx context.Context, request httpapi.RunStartRequest) (agentworkflow.Manifest, error) {
	return (Compiler{Store: s.Store}).CompileRun(ctx, request)
}

func (c Compiler) CompileRun(ctx context.Context, request httpapi.RunStartRequest) (agentworkflow.Manifest, error) {
	if c.Store == nil {
		return agentworkflow.Manifest{}, errors.New("compiler store is required")
	}
	switch request.Run.Kind {
	case spec.KindAgentRun:
		if strings.TrimSpace(request.AgentRef) == "" || request.WorkflowRef != "" {
			return agentworkflow.Manifest{}, errors.New("AgentRun requires only agentRef")
		}
		resource, err := c.Store.GetResource(ctx, request.Scope, spec.KindAgent, request.AgentRef)
		if err != nil {
			return agentworkflow.Manifest{}, fmt.Errorf("resolve agent revision: %w", err)
		}
		if resource.Digest != request.Run.DefinitionDigest {
			return agentworkflow.Manifest{}, errors.New("agent definition digest does not match applied revision")
		}
		execution, contract, timeout, err := c.compileAgentExecution(ctx, request.Scope, request.AgentRef)
		if err != nil {
			return agentworkflow.Manifest{}, err
		}
		return compileManifest(agentworkflow.Manifest{
			Name: "agent/" + request.AgentRef, Revision: resource.Digest,
			Steps: []agentworkflow.Step{{ID: "agent", AgentRef: "agent/" + request.AgentRef, Timeout: timeout, Execution: execution, Contract: contract}},
		})
	case spec.KindWorkflowRun:
		if strings.TrimSpace(request.WorkflowRef) == "" || request.AgentRef != "" {
			return agentworkflow.Manifest{}, errors.New("WorkflowRun requires only workflowRef")
		}
		resource, err := c.Store.GetResource(ctx, request.Scope, spec.KindWorkflow, request.WorkflowRef)
		if err != nil {
			return agentworkflow.Manifest{}, fmt.Errorf("resolve workflow revision: %w", err)
		}
		if resource.Digest != request.Run.DefinitionDigest {
			return agentworkflow.Manifest{}, errors.New("workflow definition digest does not match applied revision")
		}
		resources, err := spec.Decode(resource.Document)
		if err != nil || len(resources) != 1 {
			return agentworkflow.Manifest{}, errors.New("stored workflow revision is invalid")
		}
		definition, ok := resources[0].(*spec.Workflow)
		if !ok || definition.Metadata.Name != request.WorkflowRef {
			return agentworkflow.Manifest{}, errors.New("stored workflow identity does not match run")
		}
		manifest := agentworkflow.Manifest{Name: definition.Metadata.Name, Revision: resource.Digest}
		for _, step := range definition.Spec.Steps {
			compiled := agentworkflow.Step{ID: step.ID, Needs: append([]string(nil), step.Needs...)}
			if step.Agent != "" {
				compiled.AgentRef = "agent/" + step.Agent
				execution, contract, agentTimeout, compileErr := c.compileAgentExecution(ctx, request.Scope, step.Agent)
				if compileErr != nil {
					return agentworkflow.Manifest{}, fmt.Errorf("step %q: %w", step.ID, compileErr)
				}
				compiled.Execution = execution
				compiled.Contract = contract
				compiled.Timeout = agentTimeout
			}
			if len(step.Input) != 0 {
				compiled.InputRef = "definition://" + resource.Digest + "/steps/" + step.ID + "/input"
			}
			if step.Timeout != "" {
				timeout, parseErr := time.ParseDuration(step.Timeout)
				if parseErr != nil {
					return agentworkflow.Manifest{}, fmt.Errorf("step %q timeout: %w", step.ID, parseErr)
				}
				compiled.Timeout = timeout
				compiled.Execution.Resources.Timeout = timeout
			}
			if step.Retries > 0 {
				compiled.Retry.MaxAttempts = int32(step.Retries + 1)
			}
			if step.Approval != nil {
				compiled.Approval = &agentworkflow.ApprovalSpec{ID: step.ID, Reason: step.Approval.Reason, Role: step.Approval.Role}
			}
			manifest.Steps = append(manifest.Steps, compiled)
		}
		return compileManifest(manifest)
	default:
		return agentworkflow.Manifest{}, fmt.Errorf("unsupported run kind %q", request.Run.Kind)
	}
}

func (c Compiler) compileAgentExecution(ctx context.Context, scope store.Scope, name string) (runner.SandboxSpec, agentworkflow.ExecutionContract, time.Duration, error) {
	storedAgent, err := c.Store.GetResource(ctx, scope, spec.KindAgent, name)
	if err != nil {
		return runner.SandboxSpec{}, agentworkflow.ExecutionContract{}, 0, fmt.Errorf("resolve agent %q: %w", name, err)
	}
	decoded, err := spec.Decode(storedAgent.Document)
	if err != nil || len(decoded) != 1 {
		return runner.SandboxSpec{}, agentworkflow.ExecutionContract{}, 0, errors.New("stored agent revision is invalid")
	}
	agent, ok := decoded[0].(*spec.Agent)
	if !ok || agent.Metadata.Name != name || agent.Spec.SandboxProfileRef == "" {
		return runner.SandboxSpec{}, agentworkflow.ExecutionContract{}, 0, errors.New("agent identity or sandboxProfileRef is invalid")
	}
	storedProfile, err := c.Store.GetResource(ctx, scope, spec.KindSandboxProfile, agent.Spec.SandboxProfileRef)
	if err != nil {
		return runner.SandboxSpec{}, agentworkflow.ExecutionContract{}, 0, fmt.Errorf("resolve sandbox profile %q: %w", agent.Spec.SandboxProfileRef, err)
	}
	decoded, err = spec.Decode(storedProfile.Document)
	if err != nil || len(decoded) != 1 {
		return runner.SandboxSpec{}, agentworkflow.ExecutionContract{}, 0, errors.New("stored sandbox profile revision is invalid")
	}
	profile, ok := decoded[0].(*spec.SandboxProfile)
	if !ok || profile.Metadata.Name != agent.Spec.SandboxProfileRef {
		return runner.SandboxSpec{}, agentworkflow.ExecutionContract{}, 0, errors.New("stored sandbox profile identity is invalid")
	}
	contract := agentworkflow.ExecutionContract{
		Agent:           agentworkflow.RevisionRef{Kind: spec.KindAgent, Name: name, Digest: storedAgent.Digest},
		SandboxProfile:  agentworkflow.RevisionRef{Kind: spec.KindSandboxProfile, Name: profile.Metadata.Name, Digest: storedProfile.Digest},
		InstructionsRef: "definition://" + storedAgent.Digest + "/spec/instructions",
	}
	if strings.TrimSpace(agent.Spec.Instructions.Inline) == "" {
		return runner.SandboxSpec{}, agentworkflow.ExecutionContract{}, 0, errors.New("executable agents currently require inline instructions")
	}
	contract.Instructions = agent.Spec.Instructions.Inline
	if len(agent.Spec.Verification.Commands) > 0 {
		contract.VerificationRef = "definition://" + storedAgent.Digest + "/spec/verification"
		contract.Verification = append([]string(nil), agent.Spec.Verification.Commands...)
	}
	for _, skill := range agent.Spec.Skills {
		contract.InlineSkills = append(contract.InlineSkills, agentworkflow.PinnedReference{Ref: skill.Ref, Digest: skill.Digest})
	}
	for _, variable := range agent.Spec.Environment {
		if variable.Value != "" || variable.Ref == "" {
			return runner.SandboxSpec{}, agentworkflow.ExecutionContract{}, 0, fmt.Errorf("agent environment %q must use valueFrom", variable.Name)
		}
		contract.Environment = append(contract.Environment, agentworkflow.EnvironmentReference{Name: variable.Name, Ref: variable.Ref})
	}
	if agent.Spec.SkillSetRef != "" {
		contract.SkillSet, err = c.resolveRevision(ctx, scope, spec.KindSkillSet, agent.Spec.SkillSetRef)
		if err != nil {
			return runner.SandboxSpec{}, agentworkflow.ExecutionContract{}, 0, err
		}
	}
	if agent.Spec.ToolSetRef != "" {
		contract.ToolSet, err = c.resolveRevision(ctx, scope, spec.KindToolSet, agent.Spec.ToolSetRef)
		if err != nil {
			return runner.SandboxSpec{}, agentworkflow.ExecutionContract{}, 0, err
		}
	}
	if agent.Spec.ModelRouteRef != "" {
		contract.ModelRoute, err = c.resolveRevision(ctx, scope, spec.KindModelRoute, agent.Spec.ModelRouteRef)
		if err != nil {
			return runner.SandboxSpec{}, agentworkflow.ExecutionContract{}, 0, err
		}
	}
	image, digest, err := pinnedImage(agent.Spec.Runtime.Image, profile.Spec.Image)
	if err != nil {
		return runner.SandboxSpec{}, agentworkflow.ExecutionContract{}, 0, err
	}
	backend := runner.BackendContainerdRunsc
	grade := runner.IsolationEnhanced
	switch profile.Spec.Backend {
	case "gvisor", "containerd-runsc":
	case "podman":
		backend, grade = runner.BackendPodman, runner.IsolationStandard
	default:
		return runner.SandboxSpec{}, agentworkflow.ExecutionContract{}, 0, fmt.Errorf("sandbox backend %q is not implemented", profile.Spec.Backend)
	}
	timeout := 30 * time.Minute
	if agent.Spec.Limits.Timeout != "" {
		timeout, err = time.ParseDuration(agent.Spec.Limits.Timeout)
		if err != nil || timeout <= 0 {
			return runner.SandboxSpec{}, agentworkflow.ExecutionContract{}, 0, errors.New("agent timeout is invalid")
		}
	}
	cpus, err := parseCPU(profile.Spec.Resources.CPU, 1)
	if err != nil {
		return runner.SandboxSpec{}, agentworkflow.ExecutionContract{}, 0, fmt.Errorf("sandbox CPU: %w", err)
	}
	memory, err := parseBytes(profile.Spec.Resources.Memory, 512<<20)
	if err != nil {
		return runner.SandboxSpec{}, agentworkflow.ExecutionContract{}, 0, fmt.Errorf("sandbox memory: %w", err)
	}
	disk, err := parseBytes(profile.Spec.Resources.Disk, 2<<30)
	if err != nil {
		return runner.SandboxSpec{}, agentworkflow.ExecutionContract{}, 0, fmt.Errorf("sandbox disk: %w", err)
	}
	pids := profile.Spec.Resources.PIDs
	if pids <= 0 {
		pids = 128
	}
	if profile.Spec.Network.Mode != "none" && profile.Spec.Network.Mode != "brokered" {
		return runner.SandboxSpec{}, agentworkflow.ExecutionContract{}, 0, errors.New("agent sandboxes support only none or brokered network policy")
	}
	if contract.ToolSet != nil && contract.ModelRoute == nil {
		return runner.SandboxSpec{}, agentworkflow.ExecutionContract{}, 0, errors.New("a tool-enabled agent also requires a modelRouteRef")
	}
	mounts := []runner.Mount{{Kind: "workspace", Destination: "/workspace", ReadOnly: false}, {Kind: "artifact", Destination: "/artifacts", ReadOnly: true}}
	if agent.Spec.SkillSetRef != "" || len(agent.Spec.Skills) > 0 {
		mounts = append(mounts, runner.Mount{Kind: "skills", Destination: "/skills", ReadOnly: true})
	}
	sandboxUser := strings.TrimSpace(c.SandboxUser)
	if sandboxUser == "" {
		sandboxUser = "65532"
	}
	execution := runner.SandboxSpec{
		Backend: backend, IsolationGrade: grade, Image: image, ImageDigest: digest,
		RunAsUser: sandboxUser, ReadOnlyRootFS: true, NoNewPrivileges: true,
		DropAllCapabilities: true, Network: runner.NetworkNone, DirectInternet: false,
		Privileged: false, Mounts: mounts,
		Resources: runner.ResourceLimits{CPUs: cpus, MemoryBytes: memory, DiskBytes: disk, PIDs: pids, Timeout: timeout},
	}
	if err := runner.ValidateSandboxSpec(execution); err != nil {
		return runner.SandboxSpec{}, agentworkflow.ExecutionContract{}, 0, fmt.Errorf("compiled sandbox: %w", err)
	}
	return execution, contract, timeout, nil
}

func (c Compiler) resolveRevision(ctx context.Context, scope store.Scope, kind, name string) (*agentworkflow.RevisionRef, error) {
	resource, err := c.Store.GetResource(ctx, scope, kind, name)
	if err != nil {
		return nil, fmt.Errorf("resolve %s %q: %w", kind, name, err)
	}
	return &agentworkflow.RevisionRef{Kind: kind, Name: name, Digest: resource.Digest}, nil
}

func pinnedImage(agentImage, profileImage string) (string, string, error) {
	agentImage, profileImage = strings.TrimSpace(agentImage), strings.TrimSpace(profileImage)
	digest := agentImage
	image := agentImage
	if at := strings.LastIndex(agentImage, "@sha256:"); at >= 0 {
		image, digest = agentImage[:at], agentImage[at+1:]
	} else if strings.HasPrefix(agentImage, "sha256:") {
		if at := strings.LastIndex(profileImage, "@sha256:"); at >= 0 {
			image = profileImage[:at]
		} else {
			return "", "", errors.New("agent image digest requires a repository in the sandbox profile")
		}
	} else {
		return "", "", errors.New("agent image must be pinned by sha256 digest")
	}
	if image == "" || !strings.HasPrefix(digest, "sha256:") || len(digest) != 71 {
		return "", "", errors.New("agent image pin is invalid")
	}
	return image, digest, nil
}

func parseCPU(raw string, fallback float64) (float64, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return fallback, nil
	}
	if strings.HasSuffix(raw, "m") {
		value, err := strconv.ParseFloat(strings.TrimSuffix(raw, "m"), 64)
		if err != nil || value <= 0 {
			return 0, errors.New("invalid millicpu quantity")
		}
		return value / 1000, nil
	}
	value, err := strconv.ParseFloat(raw, 64)
	if err != nil || value <= 0 {
		return 0, errors.New("invalid CPU quantity")
	}
	return value, nil
}

func parseBytes(raw string, fallback int64) (int64, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return fallback, nil
	}
	multipliers := map[string]float64{"Ki": 1 << 10, "Mi": 1 << 20, "Gi": 1 << 30, "Ti": 1 << 40, "K": 1e3, "M": 1e6, "G": 1e9, "T": 1e12}
	for suffix, multiplier := range multipliers {
		if strings.HasSuffix(raw, suffix) {
			value, err := strconv.ParseFloat(strings.TrimSuffix(raw, suffix), 64)
			if err != nil || value <= 0 {
				return 0, errors.New("invalid byte quantity")
			}
			return int64(value * multiplier), nil
		}
	}
	value, err := strconv.ParseInt(raw, 10, 64)
	if err != nil || value <= 0 {
		return 0, errors.New("invalid byte quantity")
	}
	return value, nil
}

func compileManifest(manifest agentworkflow.Manifest) (agentworkflow.Manifest, error) {
	plan, err := agentworkflow.CompileManifest(manifest)
	if err != nil {
		return agentworkflow.Manifest{}, err
	}
	return agentworkflow.Manifest{Name: plan.Name, Revision: plan.Revision, Steps: plan.Steps}, nil
}
