FROM docker.io/library/golang:1.26.5@sha256:7caba5286b4c3613a337b709c573047d8ae62ee76106647313b61e72b99f20af AS build
WORKDIR /src/v3
COPY v3/go.mod v3/go.sum ./
RUN go mod download
COPY v3/ ./
RUN CGO_ENABLED=0 go build -trimpath -ldflags='-s -w' -o /out/agw-clone ./cmd/agw-clone

FROM docker.io/library/alpine:3.22.1@sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1
RUN apk add --no-cache ca-certificates git \
    && install -d -m 0700 -o 0 -g 0 /run/agw/clone \
    && install -m 0400 -o 0 -g 0 /dev/null /run/agw/clone/token \
    && test -f /run/agw/clone/token \
    && test ! -L /run/agw/clone/token
COPY --from=build /out/agw-clone /agw/clone
ENTRYPOINT ["/agw/clone"]
