apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - agents.astatide.com_agentruns.yaml
  - agents.astatide.com_agents.yaml
  - agents.astatide.com_contextstrategies.yaml
  - agents.astatide.com_gates.yaml
  - agents.astatide.com_modelroutes.yaml
  - agents.astatide.com_policies.yaml
  - agents.astatide.com_toolsets.yaml
